figment-networks/learn-web3-dapp

.gitignore
components/protocols/avalanche/steps/3_Query.tsx
components/protocols/avalanche/steps/5_Transfer_X.tsx
pages/api/avalanche/account.ts
pages/api/avalanche/transfer.ts
types/response-types.ts

@guillaumegaluz I still have some issues with the workflow of branches, commits and push/pull. I will spend some time on vacation practicing!

Use getAvalancheClient

---

.gitignore
components/protocols/near/components/Steps/Account.tsx
components/protocols/near/components/Steps/Balance.tsx
components/protocols/near/components/Steps/Call.tsx
components/protocols/near/components/Steps/Connect.tsx
components/protocols/near/components/Steps/Deploy.tsx
components/protocols/near/components/Steps/Keys.tsx
components/protocols/near/components/Steps/Transfer.tsx
components/protocols/near/components/Steps/index.ts
components/protocols/near/components/index.tsx
components/protocols/near/context/index.ts
components/protocols/near/hooks/index.ts
components/protocols/near/index.tsx
components/protocols/near/lib/index.ts
components/protocols/near/types/index.ts
pages/api/near/balance.ts
pages/api/near/callFunction.ts
pages/api/near/checkAccountId.ts
pages/api/near/connect.ts
pages/api/near/deploy.ts
pages/api/near/transfer.ts

- Removed semicolons in all TypeScript components and API routes
- All import statements now use single quotes
- Typos fixed

NEAR pathway fixes

---

README.md

Update link to correct discord server

---

components/shared/Layout/Footer.tsx
components/shared/Layout/Sidebar.tsx
lib/constants.ts

Invert split between markdown and UI + change bg of md column

---

components/shared/Layout/index.tsx

Fix issue with next btn not displaying for penultimate step

---

components/shared/Layout/Sidebar.tsx
utils/steps.ts

Add step number

---

components/shared/Layout/Sidebar.tsx
context/index.tsx

Fix position of steps

---

pages/api/celo/swap.ts

fix https://linear.app/figment-learn/issue/LEA-344/celo-pathway-swap-solution-does-not-work

Celo pathway: Swap solution does not work

---

components/protocols/polygon/index.tsx

fix https://linear.app/figment-learn/issue/LEA-342/polygon-pathway-stepids

Polygon pathway: stepId's

---

components/protocols/tezos/index.tsx

fix https://linear.app/figment-learn/issue/LEA-341/tezos-pathway-stepid-incorrect-values

Tezos pathway: stepId incorrect values

---

components/protocols/avalanche/components/nav/index.tsx
components/protocols/avalanche/components/steps/Account.tsx
components/protocols/avalanche/components/steps/Balance.tsx
components/protocols/avalanche/components/steps/Connect.tsx
components/protocols/avalanche/components/steps/Export.tsx
components/protocols/avalanche/components/steps/Import.tsx
components/protocols/avalanche/components/steps/Transfer.tsx
components/protocols/avalanche/index.tsx
components/protocols/avalanche/lib/index.ts
context/index.tsx
lib/constants.ts
types/index.ts

adapt avalanche to global state

adapt avalanche to global state

---

pages/api/celo/account.ts
pages/api/celo/connect.ts

remove celo solution

---

.env.example

removed unused ENV VAR

---

markdown/PREFACE.md

- Based on user feedback, added some clarity to the Preface, specifically:
- At some screen resolutions and in some browsers, it is not immediately clear that the left side of the UI can be scrolled.
- Some users found the Preface confusing, thinking that the example challenge there needed to be completed.

Clarify the Preface

---

.env.example
utils/datahub.ts

remove deprecated DH for Solana
https://linear.app/figment-learn/issue/LEA-453/remove-deprecated-dh-solana-url

remove deprecated DH for Solana

---

utils/datahub.ts

fix env var name

---

.env.example
pages/api/celo/account.ts
pages/api/celo/balance.ts
pages/api/celo/connect.ts
pages/api/celo/deploy.ts
pages/api/celo/getter.ts
pages/api/celo/setter.ts
pages/api/celo/swap.ts
pages/api/celo/transfer.ts
pages/api/polygon/query.ts
pages/api/secret/account.ts
pages/api/secret/balance.ts
pages/api/secret/connect.ts
pages/api/secret/deploy.ts
pages/api/secret/getter.ts
pages/api/secret/setter.ts
pages/api/secret/transfer.ts
pages/api/tezos/account.ts
pages/api/tezos/balance.ts
pages/api/tezos/connect.ts
pages/api/tezos/deploy.ts
pages/api/tezos/getter.ts
pages/api/tezos/setter.ts
pages/api/tezos/transfer.ts
pages/api/the-graph/entity.ts
pages/api/the-graph/manifest.ts
pages/api/the-graph/mapping.ts
pages/api/the-graph/node.ts
pages/api/the-graph/scaffold.ts
utils/datahub.ts

For each API route of each pathway, the error message management has been normalized.

Normalize error message

---

components/shared/CustomMarkdown/index.tsx

- Fix display of hints in markdown (Thanks @zurgl)

Fix hints in markdown

---

lib/constants.ts

- Set Ceramic pathway to inactive while improvements are made

Turn off Ceramic pathway (temporary)

---

markdown/the_graph/SUBGRAPH_QUERY.md

fix typo on graph md for the location of the file on the last step

fix typo on graph md

---

markdown/solana/PROJECT_SETUP.md

- Added instructions to clarify the Solana CLI
This addresses an issue where users might attempt to run a Test Validator before installing the Solana CLI.

Update Solana setup for Gitpod

---

components/protocols/the_graph/components/steps/Entity.tsx
components/protocols/the_graph/components/steps/Manifest.tsx
components/protocols/the_graph/components/steps/Mapping.tsx
components/protocols/the_graph/components/steps/Node.tsx
components/protocols/the_graph/components/steps/Query.tsx
components/protocols/the_graph/components/steps/Subgraph.tsx
components/protocols/the_graph/index.tsx
components/shared/Layout/Footer.tsx
hooks/useColors.ts

migrate the graph pathways to use the new reducer.

migrate the graph pathways to use the new reducer

---

markdown/solana/CHAIN_CONNECTION.md
markdown/solana/CREATE_ACCOUNT.md
markdown/solana/DEPLOY_CONTRACT.md
markdown/solana/FUND_ACCOUNT.md
markdown/solana/GET_BALANCE.md
markdown/solana/GET_CONTRACT_VALUE.md
markdown/solana/SET_CONTRACT_VALUE.md
markdown/solana/SOLANA_CREATE_GREETER.md
markdown/solana/TRANSFER_TOKEN.md

- Remove success animations as per feedback from @guillaumegaluz 
- Edits to fix typos
- Edits to clarify the solution code of some steps
- Edits to remove Discord links
- Edits to fix code blocks and hints in the Deploy step

Update Solana pathway

---

markdown/polkadot/CHAIN_CONNECTION.md
markdown/polkadot/CREATE_ACCOUNT.md
markdown/polkadot/ESTIMATE_DEPOSIT.md
markdown/polkadot/ESTIMATE_FEES.md
markdown/polkadot/GET_BALANCE.md
markdown/polkadot/RESTORE_ACCOUNT.md
markdown/polkadot/TRANSFER_TOKEN.md

- Remove success animations
- Edits for clarity

Update Polkadot pathway

---

markdown/avalanche/CHAIN_CONNECTION.md
markdown/avalanche/CREATE_KEYPAIR.md
markdown/avalanche/EXPORT_TOKEN.md
markdown/avalanche/FINAL.md
markdown/avalanche/GET_BALANCE.md
markdown/avalanche/IMPORT_TOKEN.md
markdown/avalanche/TRANSFER_TOKEN.md

- Remove success animations
- Edits to remove Discord links

Update Avalanche pathway

---

markdown/secret/CHAIN_CONNECTION.md
markdown/secret/CREATE_ACCOUNT.md
markdown/secret/DEPLOY_CONTRACT.md
markdown/secret/GET_BALANCE.md
markdown/secret/GET_CONTRACT_VALUE.md
markdown/secret/SET_CONTRACT_VALUE.md
markdown/secret/TRANSFER_TOKEN.md

- Remove success animations
- Edits for clarity

Update Secret pathway

---

markdown/tezos/CREATE_ACCOUNT.md

tezos update account step

---

markdown/near/CHAIN_CONNECTION.md
markdown/near/CREATE_ACCOUNT.md
markdown/near/CREATE_KEYPAIR.md
markdown/near/DEPLOY_CONTRACT.md
markdown/near/GET_BALANCE.md
markdown/near/GET_CONTRACT_VALUE.md
markdown/near/SET_CONTRACT_VALUE.md

- Remove success animations
- Edits for clarity
- Edits to remove Discord links

Update NEAR pathway

---

components/protocols/ceramic/components/auth/index.tsx
components/protocols/ceramic/components/steps/BasicProfile.tsx
components/protocols/ceramic/components/steps/Connect.tsx
components/protocols/ceramic/components/steps/CustomDefinition.tsx
components/protocols/ceramic/components/steps/LogIn.tsx
components/protocols/ceramic/index.tsx

migrate ceramix

---

__test__/secret.test.ts

- Tests include:
- Connection
- Generate a new keypair
- Restore a keypair from a mnemonic
- Check balance of an account (funded or not)
- Transfer using `sendTokens`

Add jest test for Secret

---

utils/context.ts

include path to solve the issue pointed out by Neco

Fix very old staled state

---

contracts/solana/program/src/lib.rs
markdown/solana/DEPLOY_CONTRACT.md

Some typo fixes I found while doing the tutorials

typo correction

---

components/protocols/polygon/challenges/transfer.ts

- remove the complete solution from Polygon's `Transfer` challenge

Fix Polygon's Transfer challenge

---

.env.example
markdown/avalanche/PROJECT_SETUP.md
markdown/celo/PROJECT_SETUP.md
markdown/near/PROJECT_SETUP.md
markdown/polkadot/PROJECT_SETUP.md
markdown/polygon/PROJECT_SETUP.md
markdown/secret/PROJECT_SETUP.md
markdown/solana/PROJECT_SETUP.md
markdown/tezos/PROJECT_SETUP.md

- Adds new images, links and instructions for DataHub API keys to all published pathways.

Update DataHub API key instructions

---

markdown/polkadot/GET_BALANCE.md
pages/api/polkadot/balance.ts

Fixes #227
Changed code based on https://github.com/jacogr/api-test-4450/blob/master/index.ts

Update Polkadot structure of get account balance

---

markdown/polygon/TRANSFER_TOKEN.md

Fix file path for Transfer step in Polygon pathway

---

markdown/ceramic/CHAIN_CONNECTION.md
markdown/polygon/CHAIN_CONNECTION.md

Contains 2 fixes: a grammar issue, and then a typo in the file pathway given.

pathways step3 edits

---

markdown/the_graph/GRAPH_NODE.md

- Fixes a typo in the pathway markdown (missing angle bracket)

Update The Graph Pathway

---

docker/docker-compose.yml
markdown/PREFACE.md
markdown/polygon/SET_CONTRACT_VALUE.md
markdown/solana/CHAIN_CONNECTION.md
markdown/solana/CREATE_ACCOUNT.md
markdown/solana/DEPLOY_CONTRACT.md
markdown/solana/FUND_ACCOUNT.md
markdown/solana/GET_BALANCE.md

Fixes for the Preface and Polygon Pathway

Pathway Maintenance
